services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: fakestore
      POSTGRES_USER: fakestoreuser
      POSTGRES_PASSWORD: fakestorepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
