# Generated by Django 5.2.6 on 2025-09-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('rating_rate', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('rating_count', models.IntegerField(null=True)),
                ('fakestore_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
